baseURL = "https://v1.soch.cc/"
languageCode = "en-us"
title = "Somē Cho"
subtitle = "Fullstack Developer"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
timeZone = "Europe/Berlin"

theme = "folio"

[languages]
[languages.en]
contentDir ='content/english'
languageName="English"
weight=1
[languages.en.params]
aboutURL = "/en/about"

[languages.de]
contentDir ='content/deutsch'
languageName="German"
weight=2
[languages.de.params]
aboutURL = "/de/über-mich"
